name: Target of workflow-run

on:
  workflow_run:
    # This has to be the `name:` of the workflow in `code_coverage.yml`.
    # Start when this  workflow has finished successfully.
    workflows: [trigger]
    types:
      - completed

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.workflow_run.pull_requests[0].url || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-22.04
    # Only run on successful pull requests. Merge commits to master upload
    # their coverage reports directly inside `code-coverage.yml`
    # TODO<joka921> Also make this work for pushes to the master branch!
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Dump Environment.
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump PR key.
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "${{ github.event.workflow_run.pull_requests[0].url}}"
