name: trigger

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.workflow_run.pull_requests[0].url || github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Dummy
        run: echo "bim"
      - name: Dump PR key.
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "${{ github.event.workflow_run.pull_requests[0].url}}"

